### ISSUE TITLE
Sikuli App.open and Mouse up/down action for mac applications

### ISSUE THREAD

**Issue by kumarkrish85** [RaiMan/SikuliX1#198]
**1. Sikuli open app action**
One of my teammate is using mac machine and i would like to know how to pass the parameter for app.open API. In case i want to open calculator application or any application software.  The below error message displayed in console

`Invalid runner: org.sikuli.script.runners.AppleScriptRunner doesn't yet support evalscript`

**2. Mouse up/down action**
Can you please share a sample scenario to understand and test the usage of mouse up and down action.

Thanks

**Comment by RaiMan** [comment]
App.open("Calculator") should open the calculator.
App.open("Safari") should open the browser.
The app-name to use usually is what is shown for the application in its menu bar top left.

A click is a combination of mouseDown() and mouseUp(). A drag-drop is a combination of mouseDown - mouseMove - mouseUp.
These low-level mouse actions are there for cases where the high-level actions (click, drag, dragDrop, ...) do not work caused by timing problems. Using the low-level actions in this case, you can play around with the timing.
So in a click in a game for example there might be needed some inner short wait (mouseDown - wait - mouseUp).
Another case is dragDrop.

**Comment by balmma** [comment]
@kumarkrish85 
> The below error message displayed in console

Is your teammate using the latest 1.1.4 snapshot?

**Comment by Shantha93** [comment]
Yes we are using 1.1.4 snapshot and i am from krish's team.

**Comment by kumarkrish85** [comment]
Hi @balmma and @RaiMan, I have 4 different actions in my tool for image drag and drop. 

1. ImgDropAt
2. ImgDrag
3. ImgDragAndDrop
4. ImgDragAndDropAt

I try to drag **"Water"** and drop to "**Alpha**" in the URL [https://gojs.net/latest/samples/htmlDragDrop.html](url)

with the ImgDrag and ImgDropAt action (In background it is using region drag and drop methods) works fine.  But when i use ImgDragAndDrop (which is using region dragdrop method) just seeing the mouse movement in Mac. Please give some input to resolve the issue

**Comment by RaiMan** [comment]
In most cases I have seen in the past, this is an inner timing problem, mostly a missing short wait before and/or after the mouseDown() at the beginning (Drag) and a missing short wait between the MouseMove() to the target and the final mouseUp() (Drop).

the sequence can be implemented as a function:
```
mouseMove(source)
wait(...) #1 might not be needed
mouseDown()
wait(...) #2 let the GUI see, you want to start a drag
mouseMove(target)
wait(...) #3 might not be needed
mouseUp()
```
My experience: the wait()'s should be for some hundred msec's.
One can start with 0.3 and decrease until it stops working.

**Comment by balmma** [comment]
> Yes we are using 1.1.4 snapshot and i am from krish's team.

It's just because the reported error message doesn't really make sense in the newest snapshot.

**Comment by balmma** [comment]
> Invalid runner: org.sikuli.script.runners.AppleScriptRunner doesn't yet support evalscript

Can you additionally provide a stacktrace please?
