### ISSUE TITLE
SikuliX API from Maven: com.sun.jna.... dependency missing 

### ISSUE THREAD

**Issue by panbaidu** [RaiMan/SikuliX1#236]
**Development environment: Idea +jdk1.8.0_231 + Windows10 + sikulixapi2.0**

> public class Demo1 {
    public static void main(String[] args) {
        Screen s = new Screen();
        ImagePath.add("src\\main\\resources\\temp.sikuli");
        Region region = Region.create(876,0,895,939);
        s.capture(region);
        try {
            s.click("1.png");
            s.write("hello world#ENTER.");
            s.wait(1);
        }catch (FindFailed | InterruptedException findFailed) {
            findFailed.printStackTrace();
        }
    }
}

_**pom.xml must add dependencies:**_
> 
       <dependency>
            <groupId>net.java.dev.jna</groupId>
            <artifactId>jna</artifactId>
            <version>5.4.0</version>
       </dependency>'
       <dependency>
            <groupId>net.java.dev.jna</groupId>
            <artifactId>jna-platform</artifactId>
            <version>5.4.0</version>
        </dependency>

**Otherwise it will report exception :**
 
>Exception in thread "main" java.lang.NoSuchMethodError: com.sun.jna.Native.load(Ljava/lang/String;Ljava/lang/Class;Ljava/util/Map;)Lcom/sun/jna/Library;
	at com.sun.jna.platform.win32.Kernel32.<clinit>(Kernel32.java:43)
        ......
       
**and**

> Exception in thread "main" java.lang.NoSuchFieldError: SIZE
	at com.sun.jna.platform.win32.WinBase.<clinit>(WinBase.java:52)
        ......

**Comment by RaiMan** [comment]
I have tested (I am working with the same environment) and principally everything is ok.

... but IDEA is a bit tricky with Maven projects and deep down deps:
 - switch on Maven-Auto-Import, so that missing deps are auto-loaded, when you open the project
 - after that you might need to rebuild the project (might not help)
 - run a `clean install` for your project ( I have a Maven run config for that (this should load the deps from Maven Central)). After that you should close/open the project. 

To see that all this might help, you should delete the branch net.jave.dev.jna in your local repository.
