### ISSUE TITLE
Option for SikuliX to not go into background (deamonize)

### ISSUE THREAD

**Issue by romangrothausmann** [RaiMan/SikuliX1#325]
It seem SikuliX has change about 7 month ago to go into background (by default) shortly after being started. This is critical when running SikuliX through a docker image because the docker container stops as soon as SikuliX goes into background, thereby loosing console output and even killing the SikuliX job. While this can be prevented by piping the output of SikuliX to `cat` (https://gitlab.com/romangrothausmann/dind-sikuli/-/commit/2233ae9b5918f707d8ed0c6a3f76828e6b96c022), this represents a very unobvious workaround. It would be much nicer if there would be an option to SikuliX to stay in foreground (e.g. `-f`) or making that the default again and having e.g. `-b` for going into background.

**Comment by RaiMan** [comment]
Are we talking about some Linux environment, where some scripts are run using a commandline like

`java -jar <path-to>/sikulix.jar -r someScript.sikuli`

Since my daily environment is not Linux and with docker I do not have any experience, I do not understand what you mean with

> deamonize and going to background

... and where or when have `-f` and `-b` have to be applied?

**Comment by romangrothausmann** [comment]
> Are we talking about some Linux environment,

Yes, to be precise within a running docker image/container like here
https://gitlab.com/romangrothausmann/dind-sikuli/-/blob/c86b8118161af8277f559d8ab23ad2dff1858791/.gitlab-ci.yml#L78

>  where some scripts are run using a commandline like `java -jar <path-to>/sikulix.jar -r someScript.sikuli`

In this case only `java -jar /opt/sikulix.jar` to get the IDE GUI.

> I do not understand what you mean with
>>    deamonize and going to background

Under Linux you can start a program from the command line such that it stays in the foreground, i.e. the input from the shell is passed to the running command, i.e. there is no shell prompt so far. If started such that it goes into background (e.g. with `&` at the end of the command), the shell prompt is back instantly but in some cases this is interpreted as if the program (now running in the background) has already exited, which seems to be the case here because the docker container exitst and stops before the GUI is up. Even when executing `java -jar /opt/sikulix.jar -h` the program goes into background quicker than the output appears, so docker quits before the output is there an so a [test on the mere CLI output](https://gitlab.com/romangrothausmann/dind-sikuli/-/blob/c86b8118161af8277f559d8ab23ad2dff1858791/.gitlab-ci.yml#L49-63) fails. Formerly this backgrounding was not happening, so the current [workaround](https://gitlab.com/romangrothausmann/dind-sikuli/-/commit/311ef3b8123eb329f803b4085385198964af1fff) to pipe to `cat` was not needed.
I could only find some info on this for c but java might be similar: https://stackoverflow.com/questions/116701/how-can-a-c-c-program-put-itself-into-background#118360
If nothing was changed in sikulix concerning this, perhaps this is some changed behavior of Java-11.

>  and where or when have -f and -b have to be applied?

That would only be a wish for an option if the going into background (deamonize) is an intended change (e.g. for its use under windows or MacOS). See e.g. `-b` option of `dhcpcd`: http://manpages.ubuntu.com/manpages/trusty/man8/dhcpcd5.8.html
I have seen the opposite behavior (by default going into background unless `-f` is provided) but cannot remember at the moment which common program that was. It is (hidden) in `-D` for `3dmod` (https://bio3d.colorado.edu/imod/doc/man/3dmod.html).

**Comment by RaiMan** [comment]
Thanks for the helpful explanations.

Since Java 9+ it is no longer possible to hack the classpath at runtime. This was done before 2.0.x and with Java 8 to get the script support on the classpath after IDE start and in 1.1.3 even by creating fat jars containing everything needed with a setup.

Now with 2.0.x and later versions, we first build a classpath after IDE start and then completely fork a new JVM with the appropriate commandline settings. The startup process in this case does not wait for the IDE process to terminate - only stdin and stderror are inherited (so IDE output, that is not redirected to the IDE message area goes to the command line window.)

In other cases (like running scripts from commandline), the startup process waits for completion.

Based on your explanation, I guess that this causes your problems.

Hence I think your suggestion, to have an option  for the GUI IDE startup process, to wait for the IDE to terminate, might be helpful.

I will make it available with 2.0.4 the next days.

**Comment by romangrothausmann** [comment]
> The startup process in this case does not wait for the IDE process to terminate
> Based on your explanation, I guess that this causes your problems.

Yes, very likely. Looking forward to test this in future version.

**Comment by RaiMan** [comment]
Closed for now. Again looked at in 2.1.0: revision of startup process.
