### ISSUE TITLE
"Export as jar" output will not run

### ISSUE THREAD

**Issue by mattrussmill** [RaiMan/SikuliX1#33]
When I perform a _File > Export as jar_ to generate a jar from the IDE and run `java -jar test_sikuli.jar` in the command prompt I get the following error: `Error: Invalid or corrupt jarfile test_sikuli.jar`.

This script will run correctly if I export via _File > Export as runnable jar_. I have been trying to perform a workaround by launching the jar via the class path `java -cp test_sikuli.jar [some path]` but have been unsuccessful finding the correct class to use.

Is there a solution or possible workaround to this problem? I am using Java Version 8 Update 181

**Comment by RaiMan** [comment]
Which version of SikuliX?

**Comment by mattrussmill** [comment]
1.1.4

**Comment by RaiMan** [comment]
I admit: neither implementation nor docs are consistent. I will fix and doc it asap to make it useable in your sense.

**Comment by Angernoxo** [comment]
I haven't been able to export any jar file, they always have invalid or corrputed jarfile.

1.1.4-SNAPSHOT-2019-02-14_12:57/Windows10.0/Java11(64)11.0.2+9-LTS

Is there any way to create JAR files? Every time I want to run Sikulix programs I make, I need to do it through the IDE,, :( any help is appreciated

**Comment by RaiMan** [comment]
@Angernoxo 
[see how to run scripts from command line](https://sikulix-2014.readthedocs.io/en/latest/faq/010-command-line.html)
for the options

instead of
``runsikulix(.cmd)``

use
``java -jar path-to/sikulixide.jar``

**The jars produced from the file menu in the IDE** are not runnable standalone. They currently need a special main script to run them from command line using SikuliX. Come back for more information about that not yet sufficiently documented/implemented option, if you want to give your scripts to someone else, so they can only be run but neither edited nor opened for looking at the code.
