### ISSUE TITLE
Running sikulixapi from command line deletes jython standalone

### ISSUE THREAD

**Issue by paulverbeke** [RaiMan/SikuliX1#352]
Hi,
First of all thanks for this amazing product, all your time already invested, and the time you will take answering me.

I'm working on maintaining [SikuliSharp](https://github.com/christianrondeau/SikuliSharp), a no longer maintained .NET wrapper for Sikuli, but in trying to set up Sikulix 2.0.4 support I noticed that calling sikulixapi.jar from command line causes the deletion of the jython-standalone-2.7.1.jar file located in the same folder, as soon as the script finishes.

I'm using this call to reproduce, but I can also just double click sikulixapi.jar to execute it and it will also delete jython:
java -jar "C:\Sikuli\sikulixapi.jar" -r "C:\Data.sikuli"

**Comment by RaiMan** [comment]
the Jython jar is moved to the <app-data>/Extensions folder, to have it available system wide.
see: https://github.com/RaiMan/SikuliX1/wiki/How-to-make-Jython-ready-in-the-IDE

Sorry, the API should be mentioned there as well, if you want to use it with -r

**Comment by paolovador** [comment]
waw thanks didn't even had the time to update my empty, missclicked new issue :)

So follow-up questions:
with this kind of call
`java -cp "C:\Sikuli\sikulixapi.jar;C:\Sikuli\jython-standalone-2.7.1.jar" org.python.util.jython "C:\Data.sikuli"`

- Do I now need to reference jython path directly from AppData.../Extensions  ?
- Is it normal that with this command (java -cp) the Sikuli project (python script + images) is not working ? I've got an error `C:\Sikuli\bin\jython.exe: No module named __main__`. I can only make it work by passing the python script path ("C:\Data.sikuli\Data.py") instead of the project folder, but then the images are not found `FindFailed: TestButton.png: (0x0) in R[0,0 1920x1080]@S(0)`

**Comment by RaiMan** [comment]
When you want to run a `.sikuli` script as you did using:
`java -cp "C:\Sikuli\sikulixapi.jar;C:\Sikuli\jython-standalone-2.7.1.jar" org.python.util.jython "C:\Data.sikuli\Data.py"`

then all the automatics done by SikuliX before running the script (sys.path, image path, standard imports, ...) are not processed.
... and yes, then you have to use the pointer to `<appdata>...` to reference jython in the classpath.

If this is your standard use case, then it is better, to install Jython on your system and revise the extensions.txt accordingly (use case 2 at https://sikulix-2014.readthedocs.io/en/latest/scenarios.html#setup-your-own-jython-environment).

In any case, when you run scripts directly with Jython, you need 
```
import org.sikuli.script.SikulixForJython
from sikuli import *
```
at the beginning of your main script.

To access images, you may use `setBundlePath()` (in your case this would be r"C:\Data.sikuli")

I just realised, that this hint did not make its way from the SikuliX-2014 wiki to the current docs.
