### ISSUE TITLE
Run from Step or Line Number

### ISSUE THREAD

**Issue by kaltinril** [RaiMan/SikuliX1#36]
Would it be possible to add some sort of "Run from this step" or "Run from this line number" feature?

For instance, you're developing a script and it fails halfway through, I don't want to start from the beginning each time.

Or, perhaps I'm just not efficiently using it and I should develop or code differently?

**Comment by RaiMan** [comment]
This is a request since years ;-)

It is principally possible, yes, but has its caveats.

Until version 1.1.3 I always told people, they might use the interactive mode from command line. But this of course has its limitations.
... and is no longer available with 1.1.4 due to implementation issues.

So I have the "pressure" to offer some solution and I will do that:
Right-click on the line number will offer:
 - run to this line from top
 - run this line (if two or more lines are selected: run selection)
 - run from this line to end

The caveats:
You must really know what you are doing, because the one interpreter session remembers the history until now, especially variable/object states. 
If we would reset the interpreter to start-up, then on the other hand variables might not be defined or do not have a suitable state.

I will not offer a solution for this due to complexity, only the bare execution option as mentioned above.

**Comment by RaiMan** [comment]
I have added the features (2018-10-09 build #106) as mentioned in the comment before for now only for Jython scripting.
Some tests would be appreciated.

**Comment by kaltinril** [comment]
I'll look into testing, I've only ran things from the UI or command line. 

Not sure how to begin with testing jython. 

Your previous reply has lots of information, but I wasn't sure if you were providing reasons it can go wrong or?  

You say there is an entry in the run menu called run selection

**Comment by RaiMan** [comment]
implemented

**Comment by kaltinril** [comment]
Nice, I finally had some time at work to test this.  I like that it retains context (variables, positions, etc).  I also like that it hides/minimizes Sikulix to prevent type("foo bar") from going into the window.

Now to try if the other items you've closed I can get past :)

Thank you!
