### ISSUE TITLE
Missing part of source code

### ISSUE THREAD

**Issue by louispham102** [RaiMan/SikuliX1#39]
Hi Raiman,
I'm using your source code by download in github. Because I want to use alone sikulixapi.jar only not contain extend libraries (slf4j include sikulixapi.jar file is not working in my project and if I use other slf4j, it will conflict) so I download source to build not include slf4j, but com.sikulix.vnc.*; is missing, I can't find it and build .jar file, can use show me where I can find it or share me sikulixapi.jar file not include slf4j. Thanks

**Comment by RaiMan** [comment]
Just removed the slf4j dependency, since not needed.

So the newest snapshot should be useable for you now.

The "missing source code" is because it is in another dependency.

Generally, you should not work with only the source code, but with a fork of the repo and use "clean install" after modifications to get the SikuliX artefacts. This gives you a chance, to pull recent changes.
