### ISSUE TITLE
Windows: How to type Not supported characters: ã, á, à, ... 

### ISSUE THREAD

**Issue by lipnotic** [RaiMan/SikuliX1#517]
**WORKAROUND** for SikuliX up to 2.0.5 for Python scripting:

Thanks @lipnotic: https://github.com/lipnotic/sikuli-type_alt

---

I´m getting this error when using **type()** accented chars like ã,ó,í,ô,é,ê and so on...
[error] java.lang.IllegalArgumentException ( java.lang.IllegalArgumentException: Key: Not supported character: ã )

I´ve tryied to update JAVA from Temurin 11 (LTS) to Temurin 16 and now using Temurin 17 (LTS) with no success in all of then. 
BTW I´m using sikuliide 2.0.5 on win64 ambient.
Any idea how to solve this?

Thanks in advance

Felipe Garbin
```
#Simple code for testing here:
keyDown(Key.WIN)
type("r")
keyUp(Key.WIN)
txt="maçã,leão,paçocão"
type(ucode(txt))
```

**Comment by RaiMan** [comment]
use paste() to type text containing non-ascii characters

**Comment by lipnotic** [comment]
> use paste() to type text containing non-ascii characters

Thanks by your answer Raimund but it doesn't solve my demand...
The field requires a "type and search" entry... Pasting content is not allowed. Actually simply don't work.
I´ve alrealdy make a wide research in Ssikuli/Jython enviroment and realized that this is really a old request.
Thanks anyway and congrats by the amazing job with sikuli (using for almost 10 years)
Felipe Garbin

**Comment by RaiMan** [comment]
Thanks for kind feedback.

What about pasting one character after the other?

If it does not work: With 2.0.5 on Windows the actual keyboard layout should be detected automatically.
(`Settings.AutoDetectKeyboardLayout = true`)

With `AutoDetectKeyboardLayout = false` internally a PC-EN-US layout is used. If you find out how to produce your non-ascii character with this layout, then you might try with the basic key methods to simulate each character one after the other.

Over the weekend I will have a look into the implementation to find out, what is possible.

**Comment by RaiMan** [comment]
Found a rather complete article:
https://blog.pcrisk.com/windows/13360-how-to-type-characters-with-accents-in-windows-10#type-in-accented-characters-using-on-screen-keyboard

I tested the case using ALT-Numpad keys like `ALT-0227` to get a `ã`

This worked:
```
keyDown(Key.ALT)
type(Key.NUM0)
type(Key.NUM2)
type(Key.NUM2)
type(Key.NUM7)
keyUp()
```

Looks a bit weird, but if packed in an intelligent def, it should work.

The needed codes can be found in the Windows Character Map App.

**Comment by lipnotic** [comment]
Raimund! I got it to work!
I've made a mix of function, research, and adequation.

I´ve created a sikuli module with a Python dictionary.
It´s working really fine here!
It uses the Win ALT codes to generate special chars...
I´ll finish it´s documentation and comments and will share. 😉
Thanks!
Felipe Garbin

**Comment by RaiMan** [comment]
Where did you get the list of `Win ALT codes`?

I am looking for a loadable list, that could be used internally to type something offending using ALT+NNNN.

**Comment by lipnotic** [comment]
Solved! I´ve created a module for us! 👊🏻😉

[https://github.com/lipnotic/sikuli-type_alt](https://github.com/lipnotic/sikuli-type_alt)

**Comment by RaiMan** [comment]
I want to keep this open, since I am working on a more general solution for 2.0.6+ (Java level).
Your module helps for SikuliX up to 2.0.5 for Python scripts.

**Comment by RaiMan** [comment]
implemented. tested in Windows and macOS. To be added to the docs.

**type(Windows):**
- what is available on/with the currently selected keyboard layout can be used with type
- if not available internally it is tried to use the ALT+Code trick based on the unicode representation of the given character

**type(Mac):**
- what is available based on a subset of the US-keyboard layout can be used with type
- if not available, then internally it is tried to use ALT+Code (temp switch to unicode-hex-layout) based on the unicode representation of the given character (rather slow)

**type(Linux)**
still the US_keyboard-layout based implementation with the known restrictions (use paste() instead if possible)

**typex(Windows, Mac)**
- A new feature, that allows to type based on the unicode representation of a character 
(using the above mentioned solutions - hence rather slow on Mac)
- if `characters` are given, it works like `type()`
- the `following 3 parameter versions` type only one character per use of typex
- a string `"0xABCD"` is taken as the hex representation of a unicode character 
- an `integer number` is taken as the integer value of a unicode representation (10-based-number of a hex value)
- a `string containing only digits 0-9` is taken as an integer number (see before)

**problem on Mac**
- due to a system bug unicode characters having a hex value like 0x0..0 (first and last digit is zero) will not be typed.
- a prominent example is `à` (`0x00E0`), where even ```type("`a")``` does not work, because ``` `(grave)``` is ```0x0060```.

**Comment by jswolf19** [comment]
I've run into this problem with strings containing Japanese. I've lightly tested a solution that works on Windows in Python for SikuliX 2.0.5 with general unicode characters. (Haven't tested it with surrogates, though)

```python
def utype(ustr):
    numKeys = [Key.NUM0, Key.NUM1, Key.NUM2, Key.NUM3, Key.NUM4, Key.NUM5, Key.NUM6, Key.NUM7, Key.NUM8, Key.NUM9]

    buf = []
    for c in ustr:
        cp = ord(c)
        if cp <= 255:
            buf.append(c)
        else:
            type("".join(buf))
            buf = []
            
            keyDown(Key.ALT)
            type("".join(numKeys[int(d)] for d in str(ord(c))))
            keyUp(Key.ALT)

    type("".join(buf))
```
