### ISSUE TITLE
[1.1.4] SikulixLibs directory is empty - fixed build #153 / snapshot 20181220.142335-67

### ISSUE THREAD

**Issue by DeniDoman** [RaiMan/SikuliX1#62]
Hi Sikulix folks,

After 19-Dec changes SikulixLibs doesn't contain any dll's which leads to following exception:

`Sikulix fatal error: loadlib: opencv_java342.dll not in any libs folder`

I am using sikulixapi 1.1.4-SNAPSHOT version via Maven on Windows 10. Also I didn't check it 20-Dec evening, so maybe your last changes have fixed the problem.

**Comment by RaiMan** [comment]
Sorry for the inconvenience.

fixed build #153 / snapshot 20181220.142335-67

**Comment by DeniDoman** [comment]
Great, thank you! Also maybe it will be better to add 1.1.4 release version to repo (in addition to 1.1.4-SNAPSHOT repo) to prevent this issues in future?

**Comment by RaiMan** [comment]
> to add 1.1.4 release version

Due to private priorities, a final 1.1.4 (then available in MavenCentral) will only be available somewhen in the 1st quarter.

> to prevent this issues in future?

I will revise my testing, to use the uploaded latest snapshot jar's at least in cases like this and also test on Windows and Ubuntu as often as possible (developing on Mac ;-)

**A redesign-goal for 1.1.5/2.0:**
bundle the system-specific and package-related aspects in dedicated classes and hide the features behind a generic internal API.
Currently these aspects are scattered around and some solutions are different in some features, which is a big risk for "not expected";-) regressions.
