### ISSUE TITLE
warning message window 10 and java 10.0.1

### ISSUE THREAD

**Issue by gshields** [RaiMan/SikuliX1#8]
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.sikuli.ide.CloseableModernTabbedPaneUI (file:/E:/p-tools/sikulix/sikulix.jar) to constructor javax.swing.plaf.basic.BasicTabbedPaneUI$Actions(java.lang.String)
WARNING: Please consider reporting this to the maintainers of org.sikuli.ide.CloseableModernTabbedPaneUI
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

java 10.0.1 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)

Microsoft Windows [Version 10.0.17134.137]

**Comment by RaiMan** [comment]
... sorry, but cannot be switched off and hence has to be accepted when using Java versions 9 or 10.

Since I will not revise the IDE, we have to be prepared, that the SikuliX IDE will not be useable anymore somewhen in the future with newer versions of Java beyond version 8, which has LTS (long term support).

If this happens (hopefully not before 2020), then you either have to stay with a Java 8 version to run the SikuliX IDE  or switch to SikuliX version 2, which will be available (hopefully early ;-) in 2019 and uses some existing package as IDE (e.g. JEdit or Atom or similar with a SikuliX plugin).

**Comment by RaiMan** [comment]
still has to be accepted even with Java 11
